import pandas as pd
from hydroevaluate.utils.heutils import gee_gpm_to_1h_data
import os
from loguru import logger

def test_gee_single_basin_gpm_to_1h_data(tmp_path = 'data/gee_gpm'):
    # Create a temporary CSV file as if it is generated by gee
    csv_path = os.path.join(tmp_path, "test_data.csv")
    data = pd.DataFrame({
        "time_start": pd.date_range(start="2022-01-01", periods=10, freq="30T"),
        "BASIN_ID": ['01', '01', '01', '01', '01', '01', '01', '01', '01', '01'],
        "precipitationCal": [0.5, 0.8, 1.2, 0.3, 0.6, 0.9, 1.5, 0.7, 0.4, 1.0]
    })
    logger.info(f"Orignal Data: {data}")
    data.to_csv(csv_path, index=False)
    
    # Call the gee_gpm_to_1h_data function
    result = gee_gpm_to_1h_data(csv_path)
    logger.warning(f"Processed GPM: {result}")
    
    # Perform assertions to validate the result
    assert isinstance(result, pd.DataFrame)
    assert result.shape == (5, 3)
    assert result.columns.tolist() == ["basin", "precipitationCal", "time"]
    assert result["basin"].dtype == object
    assert result["precipitationCal"].dtype == float
    assert result["time"].dtype == "datetime64[ns]"
    # Add more assertions as needed to validate the result