# record version info here as the following format:
data_cfgs:
  sub: "/aiff_config"
  source: "GPM_GFS"
  source_path: "gpm_gfs_data"
  source_region: "US"
  download: 0
  ctx: [1]
  dataset: "GPM_GFS_Dataset"
  sampler: "WuSampler"
  scaler: "GPM_GFS_Scaler"
  rolling: False

model_cfgs:
  model_name: "SPPLSTM"
  weight_dir: "test_data/models/model_v20.pth"
  model_hyperparam:
    seq_length: 168
    forecast_length: 24
    n_output: 1
    n_hidden_states: 80

training_cfgs:
  train_epoch: 80
  save_epoch: 1
  te: 80
  batch_size: 128
  loss_func: "RMSESum"
  opt: "Adam"
  lr_scheduler: {1: 1e-4, 2: 5e-5, 3: 1e-5}
  which_first_tensor: "sequence"
  continue_train: False
  
train_period: ["2019-01-01", "2019-01-31"]
test_period: ["2019-01-01", "2019-01-31"]

gage_id:
  - '21401550'

var_out: ["streamflow"]
var_t: ["tp"]
