# record version info here as the following format:
data_cfgs:
  sub: "/v001"
  source: "GPM_GFS"
  source_path: "gpm_gfs_data"
  source_region: "US"
  download: 0
  ctx: [0]
  dataset: "GPM_GFS_Dataset"
  sampler: "WuSampler"
  scaler: "GPM_GFS_Scaler"

model_cfgs:
  model_name: "SPPLSTM"
  model_hyperparam:
    seq_length: 168
    forecast_length: 24
    n_output: 1
    n_hidden_states: 80

training_cfgs:
  train_epoch: 1
  save_epoch: 1
  te: 1
  batch_size: 128
  loss_func: "RMSESum"
  opt: "Adam"
  lr_scheduler: { 1: 5e-4, 2: 1e-4, 3: 1e-5 }
  which_first_tensor: "sequence"

train_period: ["2017-01-10", "2017-03-21"]
test_period: ["2019-03-21", "2019-04-10"]
valid_period: ["2017-04-11", "2017-04-28"]

gage_id:
  - "05584500"
  - "01544500"
  - "01423000"

var_out: ["waterlevel"]
var_t: ["tp"]
