# record version info here as the following format:
data_cfgs:
  sub: "/aiff_config"
  source: "GPM_GFS"
  source_path: "gpm_gfs_data"
  source_region: "US"
  download: 0
  ctx: [1]
  dataset: "GPM_GFS_Dataset"
  sampler: "WuSampler"
  scaler: "GPM_GFS_Scaler"
  rolling: False
  "constant_cols": [
    "area",
    "ele_mt_smn",
    "slp_dg_sav",
    "sgr_dk_sav",
    "for_pc_sse",
    "glc_cl_smj",
    "run_mm_syr",
    "inu_pc_slt",
    "cmi_ix_syr",
    "aet_mm_syr",
    "snw_pc_syr",
    "swc_pc_syr",
    "gwt_cm_sav",
    "cly_pc_sav",
    "dor_pc_pva"
  ]

model_cfgs:
  model_name: "SPPLSTM2"
  weight_dir: "test_data/models/best_model.pth"
  model_hyperparam:
    seq_length: 168
    forecast_length: 24
    n_output: 1
    n_hidden_states: 80
    dropout: 0.25

training_cfgs:
  train_epoch: 80
  save_epoch: 1
  te: 80
  batch_size: 128
  loss_func: "RMSESum"
  opt: "Adam"
  lr_scheduler: {1: 1e-4, 2: 5e-5, 3: 1e-5}
  which_first_tensor: "sequence"
  continue_train: False

test_cfgs:
  metrics: ['NSE', 'KGE', 'Bias', 'RMSE']
  
train_period: ["2017-07-01", "2017-09-29"]
test_period: ["2017-07-01", "2017-09-29"]

var_out: ["streamflow"]
var_t: ["tp"]
